github.com:
    users:
        shaggy0397:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: shaggy0397
